/**
 * 🔍 GRAPHQL QUERIES - CONSULTAS DE USUARIOS PROVEEDOR Y TIPO DOCUMENTO
*/

// Usuario Proveedor queries
export {
  GET_USUARIOS_PROVEEDOR_QUERY,
  GET_USUARIO_PROVEEDOR_QUERY,
  GET_USUARIO_PROVEEDOR_BY_DNI_QUERY,
  GET_USUARIO_PROVEEDOR_BY_USERNAME_QUERY,
  GET_USUARIOS_PROVEEDOR_BY_PROVEEDOR_ID_QUERY
} from './usuario-proveedor.queries';

// Tipo Documento queries
export {
  GET_TIPOS_DOCUMENTO_QUERY,
  GET_TIPO_DOCUMENTO_QUERY,
  GET_TIPOS_DOCUMENTO_ACTIVOS_QUERY,
  GET_TIPOS_DOCUMENTO_INACTIVOS_QUERY
} from './tipo-documento.queries';

// Tipo Solicitud Pago queries
export {
  LISTAR_TIPOS_SOLICITUD_PAGO_QUERY,
  OBTENER_TIPO_SOLICITUD_PAGO_QUERY,
  FIND_ACTIVOS_SOLICITUD_PAGO_QUERY,
  FIND_INACTIVOS_SOLICITUD_PAGO_QUERY
} from './tipo-solicitud-pago.queries';

// Upload queries
export {
  OBTENER_UPLOAD_CONFIG_QUERY
} from './upload.queries';

