/**
 * 🔍 GRAPHQL QUERIES - CONSULTAS DE USUARIOS PROVEEDOR
*/

// Usuario Proveedor queries
export {
  GET_USUARIOS_PROVEEDOR_QUERY,
  GET_USUARIOS_PROVEEDOR_PAGINADO_QUERY,
  GET_USUARIO_PROVEEDOR_QUERY,
  GET_USUARIO_PROVEEDOR_BY_DNI_QUERY,
  GET_USUARIO_PROVEEDOR_BY_USERNAME_QUERY,
  GET_USUARIOS_PROVEEDOR_BY_PROVEEDOR_ID_QUERY
} from './usuario-proveedor.queries';

// Categoria Checklist queries
export {
  LISTAR_CATEGORIAS_CHECKLIST_QUERY,
  OBTENER_CATEGORIA_CHECKLIST_QUERY,
  FIND_ACTIVAS_CATEGORIA_CHECKLIST_QUERY,
  FIND_INACTIVAS_CATEGORIA_CHECKLIST_QUERY
} from './categoria-checklist.queries';

// Plantilla Checklist queries
export {
  LISTAR_PLANTILLAS_CHECKLIST_QUERY,
  OBTENER_PLANTILLA_CHECKLIST_QUERY,
  FIND_ACTIVAS_PLANTILLA_CHECKLIST_QUERY,
  FIND_INACTIVAS_PLANTILLA_CHECKLIST_QUERY
} from './plantilla-checklist.queries';

// Upload queries
export {
  OBTENER_UPLOAD_CONFIG_QUERY
} from './upload.queries';

// Orden Compra queries
export {
  LISTAR_ORDENES_COMPRA_QUERY
} from './orden-compra.queries';

// Expediente Pago queries
export {
  LISTAR_EXPEDIENTES_PAGO_QUERY,
  OBTENER_EXPEDIENTE_PAGO_QUERY,
  OBTENER_EXPEDIENTE_POR_OC_ID_QUERY,
  OBTENER_EXPEDIENTE_POR_CODIGO_QUERY,
  OBTENER_EXPEDIENTES_POR_PROVEEDOR_QUERY,
  OBTENER_EXPEDIENTE_COMPLETO_QUERY
} from './expediente-pago.queries';

// Proveedor queries
export {
  LISTAR_PROVEEDORES_QUERY,
  LISTAR_PROVEEDORES_PAGINATED_QUERY,
  OBTENER_PROVEEDOR_POR_ID_QUERY,
  BUSCAR_PROVEEDOR_POR_RUC_QUERY,
  LISTAR_PROVEEDORES_SUBCONTRATA_QUERY,
  OBTENER_ESTADISTICAS_COTIZACIONES_QUERY,
  CREAR_PROVEEDOR_MUTATION,
  ACTUALIZAR_PROVEEDOR_MUTATION,
  ELIMINAR_PROVEEDOR_MUTATION
} from './proveedor.queries';

// Código acceso queries
export {
  GENERAR_CODIGOS_COMPLETOS_MUTATION,
  VERIFICAR_CODIGO_ACCESO_QUERY,
  MARCAR_CODIGO_COMO_USADO_MUTATION,
  LISTAR_CODIGOS_ACCESO_QUERY,
  INVALIDAR_CODIGO_MUTATION
} from './codigo-acceso.queries';

// Tipo Pago OC queries
export {
  LISTAR_TIPOS_PAGO_OC_QUERY,
  OBTENER_TIPO_PAGO_OC_QUERY,
  OBTENER_TIPOS_PAGO_POR_EXPEDIENTE_QUERY,
  VALIDAR_CREACION_SOLICITUD_QUERY
} from './tipo-pago-oc.queries';

// Documento OC queries
export {
  LISTAR_DOCUMENTOS_OC_QUERY,
  OBTENER_DOCUMENTO_OC_QUERY,
  OBTENER_DOCUMENTOS_POR_EXPEDIENTE_QUERY,
  VERIFICAR_DOCUMENTOS_OBLIGATORIOS_APROBADOS_QUERY,
  OBTENER_DOCUMENTOS_OBLIGATORIOS_PENDIENTES_QUERY
} from './documento-oc.queries';

// Solicitud Pago queries
export {
  OBTENER_SOLICITUDES_POR_EXPEDIENTE_QUERY
} from './solicitud-pago.queries';

// Reporte solicitud pago queries
export {
  LISTAR_REPORTES_POR_SOLICITUD_PAGO_QUERY,
  LISTAR_REPORTES_SOLICITUD_PAGO_POR_PROVEEDOR_QUERY,
  LISTAR_REPORTES_SOLICITUD_PAGO_ADMIN_QUERY,
  OBTENER_REPORTE_SOLICITUD_PAGO_QUERY,
} from './reporte-solicitud-pago.queries';

// Aprobaciones Kanban
export {
  GET_KANBAN_DATA_APROBACIONES_QUERY,
  KANBAN_APROBACION_PAGE_SIZE,
  LISTAR_APROBACIONES_KANBAN_QUERY,
} from './aprobacion-kanban.queries';

export {
  APROBACION_POR_ENTIDAD_QUERY,
  APROBACION_REVISION_POR_ENTIDAD_QUERY,
  DETALLE_CHECKLIST_REVISION_APROBACION_QUERY,
} from './aprobaciones-revision.queries';
