/**
 * 🔍 GRAPHQL QUERIES - CONSULTAS DE USUARIOS PROVEEDOR Y TIPO DOCUMENTO
*/

// Usuario Proveedor queries
export {
  GET_USUARIOS_PROVEEDOR_QUERY,
  GET_USUARIO_PROVEEDOR_QUERY,
  GET_USUARIO_PROVEEDOR_BY_DNI_QUERY,
  GET_USUARIO_PROVEEDOR_BY_USERNAME_QUERY,
  GET_USUARIOS_PROVEEDOR_BY_PROVEEDOR_ID_QUERY
} from './usuario-proveedor.queries';

// Tipo Documento queries
export {
  GET_TIPOS_DOCUMENTO_QUERY,
  GET_TIPO_DOCUMENTO_QUERY,
  GET_TIPOS_DOCUMENTO_ACTIVOS_QUERY,
  GET_TIPOS_DOCUMENTO_INACTIVOS_QUERY
} from './tipo-documento.queries';

// Categoria Checklist queries
export {
  LISTAR_CATEGORIAS_CHECKLIST_QUERY,
  OBTENER_CATEGORIA_CHECKLIST_QUERY,
  FIND_ACTIVAS_CATEGORIA_CHECKLIST_QUERY,
  FIND_INACTIVAS_CATEGORIA_CHECKLIST_QUERY
} from './categoria-checklist.queries';

// Plantilla Checklist queries
export {
  LISTAR_PLANTILLAS_CHECKLIST_QUERY,
  OBTENER_PLANTILLA_CHECKLIST_QUERY,
  FIND_ACTIVAS_PLANTILLA_CHECKLIST_QUERY,
  FIND_INACTIVAS_PLANTILLA_CHECKLIST_QUERY
} from './plantilla-checklist.queries';

// Upload queries
export {
  OBTENER_UPLOAD_CONFIG_QUERY
} from './upload.queries';

